package com.ethscalper.cockpit;

import org.junit.Test;
import java.util.*;
import static org.junit.Assert.*;

public final class MultiMarketV2340Test {
    @Test public void productionRegistryIsOrderedEthThenSol(){MarketRegistry r=MarketRegistry.production();assertEquals(2,r.size());assertEquals("ETHUSDT",r.tradedMarkets().get(0).symbol);assertEquals("SOLUSDT",r.tradedMarkets().get(1).symbol);}
    @Test(expected=IllegalArgumentException.class) public void unknownSymbolNeverFallsBackToEth(){MarketRegistry.production().require("XRPUSDT");}
    @Test public void solProfileUsesExactReferenceConstants(){MarketProfile p=MarketProfile.sol();assertEquals(.015,p.aMinimumReference,0);assertEquals(.03147,p.p02AppearanceFloorReference,0);assertEquals(.03,p.stopMinimumReference,0);assertEquals(.10,p.stopMaximumReference,0);assertEquals(.12,p.targetFloorReference,0);assertEquals(.23,p.targetMaximumReference,0);assertEquals(.06,p.resultRoundTripCostReference,0);assertEquals(.10,p.riskExecutionAllowanceReference,0);}
    @Test public void solScalingAtReferenceIsTickSafe(){MarketProfile p=MarketProfile.sol();assertEquals(.02,p.scaledMinimum(.015,75.8),0);assertEquals(.03,p.scaledMinimum(.03,75.8),0);assertEquals(.10,p.scaledMaximum(.10,75.8,.03),0);}
    @Test public void solScalingAtHalfPriceKeepsCapsAboveMinimums(){MarketProfile p=MarketProfile.sol();double e=37.9,min=p.scaledMinimum(.03,e),cap=p.scaledMaximum(.10,e,min);assertTrue(min>=.01);assertTrue(cap>=min);assertTrue(p.scaledMaximum(.23,e,p.scaledMinimum(.12,e))>=p.scaledMinimum(.12,e));}
    @Test public void solScalingAtDoublePriceKeepsCapsAboveMinimums(){MarketProfile p=MarketProfile.sol();double e=151.6,min=p.scaledMinimum(.03,e),cap=p.scaledMaximum(.10,e,min);assertEquals(.06,min,1e-12);assertEquals(.20,cap,1e-12);}
    @Test public void solQualityBudgetsAreExact(){MarketProfile p=MarketProfile.sol();double[] expected={10,11.14,12.28,13.41,14.55};for(int q=3;q<=7;q++)assertEquals(expected[q-3],p.qualityRiskBudget(q),0);}
    @Test public void solQualityThreeProducesCoherentQuantity(){DynamicTradePlan.Result r=plan("LONG",3);assertTrue(r.valid);assertTrue(r.finalQuantity>=50&&r.finalQuantity<=76);assertTrue(r.theoreticalMaximumLoss<=10+1e-9);}
    @Test public void solQualityFourProducesCoherentQuantity(){DynamicTradePlan.Result r=plan("LONG",4);assertTrue(r.valid);assertTrue(r.finalQuantity>=55&&r.finalQuantity<=85);assertTrue(r.theoreticalMaximumLoss<=11.14+1e-9);}
    @Test public void solQualityFiveProducesCoherentQuantity(){DynamicTradePlan.Result r=plan("LONG",5);assertTrue(r.valid);assertTrue(r.finalQuantity>=61&&r.finalQuantity<=94);assertTrue(r.theoreticalMaximumLoss<=12.28+1e-9);}
    @Test public void solQualitySixProducesCoherentQuantity(){DynamicTradePlan.Result r=plan("LONG",6);assertTrue(r.valid);assertTrue(r.finalQuantity>=67&&r.finalQuantity<=103);assertTrue(r.theoreticalMaximumLoss<=13.41+1e-9);}
    @Test public void solQualitySevenProducesCoherentQuantity(){DynamicTradePlan.Result r=plan("LONG",7);assertTrue(r.valid);assertTrue(r.finalQuantity>=72&&r.finalQuantity<=111);assertTrue(r.finalQuantity<=120);assertTrue(r.theoreticalMaximumLoss<=14.55+1e-9);}
    @Test public void solLongShortPlansAreSymmetric(){DynamicTradePlan.Result l=plan("LONG",7),s=plan("SHORT",7);assertEquals(l.stopRequired,s.stopRequired,1e-12);assertEquals(l.targetDistance,s.targetDistance,1e-12);assertEquals(l.finalQuantity,s.finalQuantity);assertEquals(75.8-l.stopLoss,s.stopLoss-75.8,1e-9);}
    @Test public void invalidSolQuotesDoNotChangeExcursion(){for(double q:new double[]{0,Double.NaN,Double.POSITIVE_INFINITY}){assertEquals(.2,DynamicTradePlan.updateAdverseExcursion60("LONG",75,q,76,.2),0);assertEquals(.2,DynamicTradePlan.updateAdverseExcursion60("SHORT",75,74,q,.2),0);}}
    @Test public void solValidQuotesUpdateExcursionSymmetrically(){assertEquals(.4,DynamicTradePlan.updateAdverseExcursion60("LONG",75,74.6,0,0),1e-12);assertEquals(.4,DynamicTradePlan.updateAdverseExcursion60("SHORT",75,0,75.4,0),1e-12);}
    @Test public void twoSymbolsCanPublishSimultaneously(){MultiMarketCoordinator c=new MultiMarketCoordinator(MarketRegistry.production());assertTrue(c.publish("ETHUSDT",state(MarketProfile.eth(),3,10),1));assertTrue(c.publish("SOLUSDT",state(MarketProfile.sol(),70,12),1));assertEquals(2,c.activePlanCount());}
    @Test public void secondPlanSameSymbolIsBlocked(){MultiMarketCoordinator c=new MultiMarketCoordinator(MarketRegistry.production());assertTrue(c.publish("ETHUSDT",state(MarketProfile.eth(),3,10),1));assertFalse(c.publish("ETHUSDT",state(MarketProfile.eth(),4,12),2));}
    @Test public void ethTerminalLeavesSolActive(){MultiMarketCoordinator c=two();assertTrue(c.terminal("ETHUSDT","TP_TOUCHED",100));assertFalse(c.runtime("ETHUSDT").hasActivePlan());assertTrue(c.runtime("SOLUSDT").hasActivePlan());}
    @Test public void solTerminalLeavesEthActive(){MultiMarketCoordinator c=two();assertTrue(c.terminal("SOLUSDT","SL_TOUCHED",100));assertFalse(c.runtime("SOLUSDT").hasActivePlan());assertTrue(c.runtime("ETHUSDT").hasActivePlan());}
    @Test public void analyticalInvalidationCannotTerminateEitherPlan(){MultiMarketCoordinator c=two();assertFalse(c.terminal("ETHUSDT","SCENARIO_INVALIDATED",100));assertFalse(c.terminal("SOLUSDT","TIMEOUT_45M",100));assertEquals(2,c.activePlanCount());}
    @Test public void independentRearmBoundaryIsExact(){MultiMarketCoordinator c=two();c.terminal("ETHUSDT","TP_TOUCHED",1_000);assertFalse(c.runtime("ETHUSDT").allowsNewPlan(180_999));assertTrue(c.runtime("ETHUSDT").allowsNewPlan(181_000));assertTrue(c.runtime("SOLUSDT").hasActivePlan());}
    @Test public void aggregateRiskIsInformationalAndAllowsSecondPlan(){MultiMarketCoordinator c=two();assertEquals(22,c.aggregateModeledRisk(),1e-12);assertEquals(2,c.activePlanCount());}
    @Test public void persistenceStoresAndRestoresBothPlansIndependently(){MemoryBackend b=new MemoryBackend();ActivePlanPersistence p=new ActivePlanPersistence(b);assertTrue(p.saveForMarket(state(MarketProfile.eth(),3,10)));assertTrue(p.saveForMarket(state(MarketProfile.sol(),70,12)));assertEquals("ETHUSDT",p.restore("ETHUSDT").state.symbol);assertEquals("SOLUSDT",p.restore("SOLUSDT").state.symbol);}
    @Test public void clearingSolDoesNotClearEth(){MemoryBackend b=new MemoryBackend();ActivePlanPersistence p=new ActivePlanPersistence(b);p.saveForMarket(state(MarketProfile.eth(),3,10));p.saveForMarket(state(MarketProfile.sol(),70,12));assertTrue(p.clearForTerminal("SOLUSDT","TP_TOUCHED"));assertNotNull(p.restore("ETHUSDT").state);assertNull(p.restore("SOLUSDT").state);}
    @Test public void corruptSolDoesNotCorruptEth(){MemoryBackend b=new MemoryBackend();ActivePlanPersistence p=new ActivePlanPersistence(b);p.saveForMarket(state(MarketProfile.eth(),3,10));b.values.put("plan.SOLUSDT.entry","broken");assertNotNull(p.restore("ETHUSDT").state);assertTrue(p.restore("SOLUSDT").invalid);}
    @Test public void legacyPlanWithoutSymbolMigratesToEth(){ActivePlanState original=state(MarketProfile.eth(),2,9);Map<String,String> map=new LinkedHashMap<>(original.toMap());map.remove("symbol");map.remove("asset");map.remove("profileVersion");map.remove("resultCostPerUnit");map.remove("riskAllowancePerUnit");map.remove("qualityRiskBudget");map.remove("theoreticalMaximumLoss");map.put("formatVersion","1");ActivePlanState migrated=ActivePlanState.fromMap(map);assertNotNull(migrated);assertEquals("ETHUSDT",migrated.symbol);assertEquals(2,migrated.quantity);}
    @Test public void terminalRearmsArePersistedPerSymbol(){TerminalMemory b=new TerminalMemory();TerminalRearmPersistence p=new TerminalRearmPersistence(b);assertTrue(p.save("ETHUSDT",10));assertTrue(p.save("SOLUSDT",20));assertEquals(10,p.restore("ETHUSDT"));assertEquals(20,p.restore("SOLUSDT"));}
    @Test public void signaturesSeparateEqualPricesAcrossSymbols(){SignalDecision e=signal(MarketProfile.eth()),s=signal(MarketProfile.sol());assertNotEquals(MarketPlanOrchestrator.signature(e,60_000),MarketPlanOrchestrator.signature(s,60_000));}
    @Test public void solOlsUsesSolMinuteClosesOnly(){List<TrendRegime60.MinuteClose> closes=new ArrayList<>();for(int i=0;i<60;i++)closes.add(new TrendRegime60.MinuteClose(i*60_000L,75+i*.01));List<TrendRegime60.Point> points=TrendRegime60.pointsFromMinuteCloses(closes,59*60_000L,75.59);assertEquals(60,points.size());assertTrue(points.get(59).price<100);}
    @Test public void fakeThirdProfileRequiresNoCoordinatorBranch(){MarketProfile fake=MarketProfile.builder("TESTUSDT","TEST","TEST_V1").referencePrice(10).priceTick(.01).quantity(1,1,10).researchCandidate(true).adaptivePriceScale(true).detection(.01,.02,.02).stops(.02,.10).targets(.05,.20).p02Seed(.05,.03).revalidation(.01,.02).lateDistances(.02,.02).costs(.01,.02).riskBudgets(1,2).qualityBudgets(1,1.2,1.4,1.6,2).staleReasonCode("TEST_STALE").build();MarketRegistry registry=new MarketRegistry(Arrays.asList(MarketProfile.eth(),MarketProfile.sol(),fake));MultiMarketCoordinator c=new MultiMarketCoordinator(registry);assertEquals("TEST",c.runtime("TESTUSDT").profile.asset);assertEquals(3,c.runtimes().size());}
    @Test public void btcIsContextOnlyAndNeverRegisteredAsTradable(){MarketRegistry r=MarketRegistry.production();assertFalse(r.contains("BTCUSDT"));assertEquals("BTCUSDT",SharedReferenceContext.SYMBOL);}
    @Test public void realTradingAlwaysRemainsDisabled(){assertFalse(SignalSafetyPolicies.realTradingAllowed());}
    @Test public void rangeFadeRemainsDiagnosticOnly(){SignalDecision fade=SignalDecision.signal(MarketProfile.sol(),"LONG","RANGE_FADE",80,3,75,75.12,74.97,.12,.03,"",true,75,75,0);MarketSnapshot s=MarketSnapshot.builder(20_001).market(MarketProfile.sol(),75,74.99,75).averages(.02,1).movement(.02,.03,.04,75.2,74.8).flowWindows(.1,.1,.1,.1).candleCounts(40,40).build();assertEquals(CandidateLifecycle.RANGE_FADE_DIAGNOSTIC_ONLY,CandidateLifecycle.processPendingCandidate(MarketProfile.sol(),fade,s,true,1,20_001,0,0,false,"P01",null).reasonCode);}

    private static DynamicTradePlan.Result plan(String side,int q){return DynamicTradePlan.calculate(MarketProfile.sol(),side,75.8,.015,0,"LONG".equals(side)?76.8:75.7,"LONG".equals(side)?75.7:74.8,q);}
    private static SignalDecision signal(MarketProfile p){return SignalDecision.signal(p,"LONG","CONTINUATION",90,3,75.8,75.92,75.77,.12,.03,"",true,75,76,1);}
    private static ActivePlanState state(MarketProfile p,int quantity,double loss){double entry=MarketProfile.ETH_SYMBOL.equals(p.symbol)?1900:75.8;double tp=entry+p.targetFloorReference,sl=entry-p.stopMinimumReference;return ActivePlanState.builder().market(p).side("LONG").family("CONTINUATION · P01").reasonCode("OK").reasonText("active").score(90).quantity(quantity).prices(entry,tp,sl).risk(tp-entry,entry-sl).times(1,1,1).notification(p.symbol+"|sig",3000+quantity).lastMarket(entry,entry-.01,entry+.01,p.aMinimumReference).lastP01ConfirmedAt(1).movement("",true,entry,entry,0).unitRisk(p.resultRoundTripCostReference,p.riskExecutionAllowanceReference,p.finalRiskBudgetUsdt,loss).build();}
    private static MultiMarketCoordinator two(){MultiMarketCoordinator c=new MultiMarketCoordinator(MarketRegistry.production());c.publish("ETHUSDT",state(MarketProfile.eth(),3,10),1);c.publish("SOLUSDT",state(MarketProfile.sol(),70,12),1);return c;}
    private static final class MemoryBackend implements ActivePlanPersistence.Backend{Map<String,String> values=new LinkedHashMap<>();public Map<String,String> readAll(){return new LinkedHashMap<>(values);}public boolean replaceAll(Map<String,String> v){values=new LinkedHashMap<>(v);return true;}}
    private static final class TerminalMemory implements TerminalRearmPersistence.Backend{Map<String,String> values=new LinkedHashMap<>();public Map<String,String> read(){return new LinkedHashMap<>(values);}public boolean write(Map<String,String> v){values=new LinkedHashMap<>(v);return true;}}
}
