package com.ethscalper.cockpit;
import org.junit.Test;import static org.junit.Assert.*;
public final class V23448ScalpActionPolicyTest {
 @Test public void rangeBoundaryAndLongRejection(){MarketSnapshot s=snap(.9526144);assertEquals(ScalpActionPolicy.RANGE_EXTREME,ScalpActionPolicy.selectRaw(sig("SHORT","RANGE"),s,m()));assertNull(ScalpActionPolicy.selectRaw(sig("LONG","RANGE"),s,m()));assertNull(ScalpActionPolicy.selectRaw(sig("SHORT","RANGE"),snap(.95261439),m()));}
 @Test public void reversalBoundaryIsInclusive(){ScalpActionContextTracker.Metrics x=new ScalpActionContextTracker.Metrics(-.00411754,true,0,true,0,true);assertEquals(ScalpActionPolicy.REVERSAL_8M,ScalpActionPolicy.selectRaw(sig("LONG","OTHER"),snap(.5),x));assertNull(ScalpActionPolicy.selectRaw(sig("LONG","OTHER"),snap(.5),new ScalpActionContextTracker.Metrics(-.00411753,true,0,true,0,true)));}
 @Test public void move3BoundaryIsInclusive(){assertEquals(ScalpActionPolicy.CONFIRM_MOVE3,ScalpActionPolicy.selectLegacy("ETHUSDT","LONG","P01",-.381534,m()));assertNull(ScalpActionPolicy.selectLegacy("ETHUSDT","LONG","P02",-.381535,m()));}
 @Test public void p01MicrovolBoundaryIsInclusive(){ScalpActionContextTracker.Metrics x=new ScalpActionContextTracker.Metrics(0,false,.0000689415,true,0,false);assertEquals(ScalpActionPolicy.P01_SHORT_MICROVOL,ScalpActionPolicy.selectLegacy("ETHUSDT","SHORT","P01",-.5,x));assertNull(ScalpActionPolicy.selectLegacy("ETHUSDT","SHORT","P02",-.5,x));assertNull(ScalpActionPolicy.selectLegacy("ETHUSDT","LONG","P01",-.5,x));}
 @Test public void coverageBoundaryAndFamily(){ScalpActionContextTracker.Metrics x=new ScalpActionContextTracker.Metrics(0,false,0,false,.982383,true);assertEquals(ScalpActionPolicy.CONT_COVERAGE,ScalpActionPolicy.selectRaw(sig("LONG","CONTINUATION"),snap(.5),x));assertNull(ScalpActionPolicy.selectRaw(sig("LONG","RANGE"),snap(.5),x));}
 @Test public void priorityIsExact(){ScalpActionContextTracker.Metrics x=new ScalpActionContextTracker.Metrics(-1,true,0,true,1,true);assertEquals(ScalpActionPolicy.RANGE_EXTREME,ScalpActionPolicy.selectRaw(sig("SHORT","CONTINUATION"),snap(.99),x));}
 @Test public void identifiersAreFrozen(){assertEquals("NMC_SCALP_ACTION_V1",ScalpActionPolicy.ENGINE_ID);assertEquals("SCALP_ACTION_V1_20260805",ScalpActionPolicy.POLICY_ID);assertEquals("SCALP_ACTION_SCHEMA_V1",ScalpActionPolicy.SCHEMA_ID);}
 private static ScalpActionContextTracker.Metrics m(){return new ScalpActionContextTracker.Metrics(0,false,1,true,0,false);}private static SignalDecision sig(String side,String family){return SignalDecision.signal(MarketProfile.eth(),side,family,1,1,1900,1901,1899,1,1,"",false,0,0,0);}private static MarketSnapshot snap(double pos){return MarketSnapshot.builder(1).eth(1900,1899.99,1900.01).btc(60000,59999,60001).averages(1,1).movement(0,0,0,1910,1890).professionalFeatures(20,1,pos,1,1,1,1,0,0,0,0,0,0,0,0,0,0).build();}
}
