package com.ethscalper.cockpit;
import org.junit.Test;import java.nio.file.*;import java.util.*;import static org.junit.Assert.*;
public final class V23448DeliveryConfigurationTest {
 @Test public void formatTwoStillRestoresWithoutExpiry(){ActivePlanState s=ActivePlanState.fromMap(base(2));assertNotNull(s);assertEquals(2,s.formatVersion);assertEquals(0,s.entryValidUntil);assertEquals("",s.engineId);}
 @Test public void formatThreeRestoresActionMetadata(){Map<String,String> m=base(3);m.put("engineId",ScalpActionPolicy.ENGINE_ID);m.put("routeId","ETH_CONFIRM_MOVE3_V1");m.put("episodeId","e");m.put("qualificationAt","1");m.put("entryValidUntil","5001");m.put("entryWindowStatus","VALIDE");ActivePlanState s=ActivePlanState.fromMap(m);assertNotNull(s);assertEquals(5001,s.entryValidUntil);}
 @Test public void noTradingAutomationAllowed(){assertFalse(SignalSafetyPolicies.realTradingAllowed());}
 @Test public void workflowAndVersionAre48()throws Exception{Path root=Paths.get(System.getProperty("user.dir")).toAbsolutePath();Path repo=Files.exists(root.resolve(".github"))?root:root.getParent();String gradle=new String(Files.readAllBytes(repo.resolve("app").resolve("build.gradle")),"UTF-8");String workflow=new String(Files.readAllBytes(repo.resolve(".github").resolve("workflows").resolve("nmc-ci.yml")),"UTF-8");assertTrue(gradle.contains("versionCode 23448"));assertTrue(gradle.contains("versionName '2.34.4.8'"));assertTrue(workflow.contains("NMC-v2.34.4.8-stable-apk"));}
 @Test public void movementRegistryHasNoTerminalCooldown(){ScalpActionMovementRegistry r=new ScalpActionMovementRegistry();ScalpActionMovementRegistry.Episode a=r.observe("ETHUSDT","LONG",1);r.markOpened(a.episodeId,"x");ScalpActionMovementRegistry.Episode opposite=r.observe("ETHUSDT","SHORT",2);assertFalse(opposite.opened);}
 @Test public void registryIsBounded(){ScalpActionMovementRegistry r=new ScalpActionMovementRegistry();for(int i=0;i<161;i++)r.observe("ETHUSDT",i%2==0?"LONG":"SHORT",i*181000L+1);assertEquals(160,r.size());}
 private static Map<String,String> base(int version){ActivePlanState s=ActivePlanState.builder().formatVersion(version).market(MarketProfile.eth()).status("ACTIVE").side("LONG").family("LEGACY").reasonCode("x").reasonText("x").score(90).quantity(1).prices(1900,1902,1899).risk(2,1).times(1,1,1).notification("sig",1).lastMarket(1900,1899,1901,.35).lastP01ConfirmedAt(0).movement("",false,0,0,0).replayRisk("","").p01(0,0,0,0,0).sizingDiagnostic("").unitRisk(1.43,0,14.55,2.43).build();return new LinkedHashMap<>(s.toMap());}
}
