package com.ethscalper.cockpit;
import org.junit.Test;import static org.junit.Assert.*;
public final class V23448ScalpActionIntegrationTest {
 @Test public void rawDecisionBuildsActionPlan(){ScalpActionEngine.Result r=engine().observeRaw(sig("SHORT","RANGE"),snap(.99),metrics(),common(),1);assertTrue(r.accepted());assertEquals(ScalpActionPolicy.RANGE_EXTREME,r.route);}
 @Test public void legacyConfirmationBuildsActionPlan(){ScalpActionEngine.Result r=engine().observeLegacy("LONG","P01",-.3,snap(.5),metrics(),common(),1);assertTrue(r.accepted());assertEquals(ScalpActionPolicy.CONFIRM_MOVE3,r.route);}
 @Test public void publicPlanBlocks(){ScalpActionEngine.Result r=engine().observeRaw(sig("SHORT","RANGE"),snap(.99),metrics(),new ScalpActionEngine.Common("ACTION_ON",true,true,true,true,false),1);assertEquals("SCALP_ACTION_PUBLIC_PLAN_ACTIVE",r.reasonCode);}
 @Test public void diagnosticsModeBuildsVirtualOnly(){ScalpActionEngine.Result r=engine().observeRaw(sig("SHORT","RANGE"),snap(.99),metrics(),new ScalpActionEngine.Common("DIAGNOSTICS_ONLY",true,true,true,false,false),1);assertTrue(r.accepted());assertTrue(r.virtualQualified);}
 @Test public void episodeDedupBlocksSecondOpen(){ScalpActionEngine e=engine();ScalpActionEngine.Result first=e.observeRaw(sig("SHORT","RANGE"),snap(.99),metrics(),common(),1);assertTrue(e.markOpened(first));assertEquals("SCALP_ACTION_DUPLICATE_EPISODE",e.observeRaw(sig("SHORT","RANGE"),snap(.99),metrics(),common(),2).reasonCode);}
 private static ScalpActionEngine engine(){return new ScalpActionEngine(new ScalpActionMovementRegistry());}private static ScalpActionEngine.Common common(){return new ScalpActionEngine.Common("ACTION_ON",true,true,true,false,false);}private static ScalpActionContextTracker.Metrics metrics(){return new ScalpActionContextTracker.Metrics(0,true,0,true,1,true);}private static SignalDecision sig(String side,String f){return SignalDecision.signal(MarketProfile.eth(),side,f,1,1,1900,1901,1899,1,1,"",false,0,0,0);}private static MarketSnapshot snap(double pos){return MarketSnapshot.builder(1).eth(1900,1899.99,1900.01).btc(1,1,1).averages(2.1,1).movement(0,0,0,1910,1890).professionalFeatures(20,1,pos,1,1,1,1,0,0,0,0,0,0,0,0,0,0).build();}
}
