package com.ethscalper.cockpit;
import org.junit.Test;import static org.junit.Assert.*;
public final class V23449CvCoreArbiterTest {
 @Test public void aBeatsC(){assertEquals(CvCorePolicy.DUAL_EXHAUSTION_SHORT.routeId,winner(result(CvCorePolicy.P02_BALANCED_SHORT,"SHORT",2),result(CvCorePolicy.DUAL_EXHAUSTION_SHORT,"SHORT",2)));}
 @Test public void bBeatsC(){assertEquals(CvCorePolicy.CAPITULATION_LONG.routeId,winner(result(CvCorePolicy.P02_BALANCED_SHORT,"SHORT",2),result(CvCorePolicy.CAPITULATION_LONG,"LONG",2)));}
 @Test public void iterationOrderDoesNotMatter(){CvCoreEngine.Result a=result(CvCorePolicy.DUAL_EXHAUSTION_SHORT,"SHORT",1),c=result(CvCorePolicy.P02_BALANCED_SHORT,"SHORT",1);assertEquals(winner(a,c),winner(c,a));}
 @Test public void oppositeSidesStillOneWinner(){CvCoreCandidateArbiter x=new CvCoreCandidateArbiter();x.beginCycle(1);x.collect(result(CvCorePolicy.DUAL_EXHAUSTION_SHORT,"SHORT",1),snap(),1);x.collect(result(CvCorePolicy.CAPITULATION_LONG,"LONG",1),snap(),1);CvCoreCandidateArbiter.Resolution r=x.resolve();assertNotNull(r.winner);assertEquals(1,r.notSelected.size());}
 @Test public void loserEpisodeRemainsUnopened(){CvCoreMovementRegistry reg=new CvCoreMovementRegistry();CvCoreEngine engine=new CvCoreEngine(reg);CvCoreMovementRegistry.Episode ea=reg.observe("ETHUSDT","SHORT",1),eb=reg.observe("ETHUSDT","LONG",1);CvCoreEngine.Result a=engine.observeRaw(CvCoreTestFixtures.signal("SHORT","RANGE_FADE"),snap(),CvCoreTestFixtures.metrics(-1,-1,0,1,0,0),CvCoreTestFixtures.common(),1,ea);CvCoreEngine.Result b=engine.observeRaw(CvCoreTestFixtures.signal("LONG","RANGE_FADE"),snap(),CvCoreTestFixtures.metrics(-1,0,0,1,-1,0),CvCoreTestFixtures.common(),1,eb);CvCoreCandidateArbiter arb=new CvCoreCandidateArbiter();arb.beginCycle(1);arb.collect(b,snap(),1);arb.collect(a,snap(),1);CvCoreCandidateArbiter.Resolution r=arb.resolve();assertTrue(engine.markOpened(r.winner.result));assertFalse(r.notSelected.get(0).result.episode.opened);}
 private static String winner(CvCoreEngine.Result a,CvCoreEngine.Result b){CvCoreCandidateArbiter x=new CvCoreCandidateArbiter();x.beginCycle(1);x.collect(a,snap(),1);x.collect(b,snap(),1);return x.resolve().winner.result.route.routeId;}
 private static CvCoreEngine.Result result(CvCorePolicy.Route route,String side,long at){CvCoreMovementRegistry reg=new CvCoreMovementRegistry();CvCoreMovementRegistry.Episode e=reg.observe("ETHUSDT",side,at);CvCoreObservation o=new CvCoreObservation("RAW","RANGE_FADE","","ETHUSDT",side,at,0,0,0,0,snap(),CvCoreTestFixtures.metrics(-1,-1,0,1,-1,0),CvCoreTestFixtures.common());CvCorePlan p=CvCorePlan.build(route,e.episodeId,side,"RAW",at,1900,1900.01,1.2,o).plan;try{java.lang.reflect.Constructor<CvCoreEngine.Result> c=CvCoreEngine.Result.class.getDeclaredConstructor(CvCorePolicy.Route.class,CvCoreMovementRegistry.Episode.class,CvCorePlan.class,String.class,CvCoreObservation.class);c.setAccessible(true);return c.newInstance(route,e,p,"",o);}catch(Exception ex){throw new AssertionError(ex);}}
 private static MarketSnapshot snap(){return CvCoreTestFixtures.snapshot(1900,1900.01,1.2,0,0);}
}
