package com.ethscalper.cockpit;
import org.junit.Test;import java.util.Map;import org.json.JSONObject;import static org.junit.Assert.*;
public final class V23449CvCoreDiagnosticsTest {
 @Test public void recorderCountsCvConfirmedAndTerminal(){MarketDiagnosticRecorder r=new MarketDiagnosticRecorder(MarketProfile.eth());r.record(1,"CV_CORE_PLAN_PERSISTED","","","","","",null,null,0,true,true,0,null);r.record(2,"CV_CORE_TP_TOUCHED","","","","","",null,null,0,true,true,0,null);Map<String,Object>s=r.summary();assertEquals(1,s.get("confirmedTrades"));assertEquals(1,s.get("tp"));assertEquals(0,s.get("sl"));}
 @Test public void summaryEconomicsAreExact(){CvCoreSummary s=new CvCoreSummary();CvCorePlan p=CvCoreTestFixtures.plan(CvCorePolicy.DUAL_EXHAUSTION_SHORT,"SHORT");s.opened();s.terminal(p.observe(2,p.takeProfit-.01,p.takeProfit,true));CvCorePlan q=CvCoreTestFixtures.plan(CvCorePolicy.DUAL_EXHAUSTION_SHORT,"SHORT");s.terminal(q.observe(3,q.stopLoss,q.stopLoss+1,true));Map<String,Object>m=s.snapshot(false);assertEquals(1L,m.get("tp"));assertEquals(1L,m.get("sl"));assertEquals((Double)m.get("netR")/2,(Double)m.get("expectancyR"),1e-12);assertNotNull(m.get("profitFactorR"));assertTrue((Double)m.get("estimatedFeesUsdt")>0);}
 @Test public void freshTimeCapsAndSkipsStale(){CvCoreSummary s=new CvCoreSummary();s.observeFresh(1000,true);s.observeFresh(11000,true);s.observeFresh(12000,false);s.observeFresh(13000,true);s.observeFresh(15000,true);assertEquals(7000L,s.snapshot(false).get("freshObservedMs"));}
 @Test public void resetClearsLiveCounters(){CvCoreSummary s=new CvCoreSummary();s.opened();s.alert();s.duplicate();s.reset();Map<String,Object>m=s.snapshot(false);assertEquals(0L,m.get("openings"));assertEquals(0L,m.get("alerts"));assertEquals(0L,m.get("duplicates"));}
 @Test public void summaryJsonSafeAndBounded(){CvCoreSummary s=new CvCoreSummary();for(int i=0;i<1000;i++)s.reject("R"+(i%10));String json=new JSONObject(s.snapshot(false)).toString();assertFalse(json.contains("NaN"));assertFalse(json.contains("Infinity"));assertTrue(json.length()<10000);}
}
