package com.ethscalper.cockpit;

import org.junit.Test;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import static org.junit.Assert.*;

/** Functional regressions for the isolated frozen future-holdout protocol. */
public final class V23447FrozenProfitabilityShadowTest {
    @Test public void ethThresholdIsStrictAndScoreDoesNotFilter(){
        SignalDecision low=signal(MarketProfile.eth(),"LONG","RANGE_FADE",1,1_900,100,90,10);
        assertFalse(FrozenProfitabilityShadowPolicy.evaluate(MarketProfile.eth(),low,snapshot(MarketProfile.eth(),1,2.18175,"LONG",1_900,0,0)).qualified);
        assertTrue(FrozenProfitabilityShadowPolicy.evaluate(MarketProfile.eth(),low,snapshot(MarketProfile.eth(),2,2.181751,"LONG",1_900,0,0)).qualified);
    }
    @Test public void ethAcceptsEveryRangeFamilyAndBothSides(){for(String side:new String[]{"LONG","SHORT"})for(String family:new String[]{"RANGE_FADE","MICRO_RANGE_REVERSAL"})
        assertTrue(FrozenProfitabilityShadowPolicy.evaluate(MarketProfile.eth(),signal(MarketProfile.eth(),side,family,0,1900,100,90,10),snapshot(MarketProfile.eth(),1,2.2,side,1900,0,0)).qualified);}
    @Test public void ethRejectsWrongFamilyAndSymbol(){assertFalse(FrozenProfitabilityShadowPolicy.evaluate(MarketProfile.eth(),signal(MarketProfile.eth(),"LONG","CONTINUATION",99,1900,100,90,10),snapshot(MarketProfile.eth(),1,2.2,"LONG",1900,0,0)).qualified);}
    @Test public void ethLongGeometryAndFeeAwareSizingAreExact(){FrozenProfitabilityShadowPlan p=build(MarketProfile.eth(),"LONG",1923.89,2.186,3,1.5,"ETH");
        assertEquals(1930.44,p.tp,.000001);assertEquals(1920.61,p.sl,.000001);assertEquals(6.55,p.roundedTargetDistance,.000001);assertEquals(3.28,p.roundedStopDistance,.000001);assertEquals(1.43,p.cost,.000001);assertEquals(3,p.quantity,0);}
    @Test public void ethShortGeometryAndNetRRAreExact(){FrozenProfitabilityShadowPlan p=build(MarketProfile.eth(),"SHORT",1933.19,2.272,3,1.5,"ETH");
        assertEquals(1926.38,p.tp,.000001);assertEquals(1936.60,p.sl,.000001);assertEquals(6.81,p.roundedTargetDistance,.000001);assertEquals(3.41,p.roundedStopDistance,.000001);assertEquals(1.112,p.plannedNetRewardRisk,.002);}
    @Test public void solThresholdsAndFormulaAreStrict(){MarketProfile p=MarketProfile.sol();SignalDecision d=signal(p,"LONG","SCALP_CONTINUATION",0,73.57,70,74,4);
        assertFalse(FrozenProfitabilityShadowPolicy.evaluate(p,d,snapshot(p,1,.05775,"LONG",73.57,2,0)).qualified);
        double m8=0,m3=FrozenProfitabilityShadowPolicy.SOL_ACCEL_THRESHOLD*3;
        assertFalse(FrozenProfitabilityShadowPolicy.evaluate(p,d,snapshot(p,2,.058,"LONG",73.57,m3,m8)).qualified);
        assertTrue(FrozenProfitabilityShadowPolicy.evaluate(p,d,snapshot(p,3,.058,"LONG",73.57,m3+.000003,m8)).qualified);}
    @Test public void solDoesNotUseM1OrScore(){MarketProfile p=MarketProfile.sol();SignalDecision d=signal(p,"SHORT","CONTINUATION",0,73.57,70,74,4);
        FrozenProfitabilityShadowPolicy.Evaluation e=FrozenProfitabilityShadowPolicy.evaluate(p,d,snapshotWithM1(p,1,.06,"SHORT",73.57,-50,2,0));assertTrue(e.qualified);assertEquals(2d/3d,e.accel38Directional,1e-9);}
    @Test public void solCanonicalAndRobustGeometryShareEconomicIdentity(){FrozenProfitabilityShadowPlan a=build(MarketProfile.sol(),"SHORT",73.57,.077,4,1.5,"CANONICAL");FrozenProfitabilityShadowPlan b=build(MarketProfile.sol(),"SHORT",73.57,.077,4.5,1.75,"ROBUST");
        assertEquals(a.opportunityId,b.opportunityId);assertEquals(a.entry,b.entry,0);assertEquals(a.openedAt,b.openedAt);assertEquals(73.27,a.tp,.000001);assertEquals(73.69,a.sl,.000001);assertEquals(1.333333,a.plannedNetRewardRisk,.00001);assertEquals(73.23,b.tp,.000001);assertEquals(73.71,b.sl,.000001);assertEquals(1.4,b.plannedNetRewardRisk,.00001);}
    @Test public void plannedTerminalIgnoresFavourableOvershoot(){FrozenProfitabilityShadowPlan p=build(MarketProfile.eth(),"LONG",1923.89,2.186,3,1.5,"ETH");FrozenProfitabilityShadowPlan.Terminal t=p.observe(2_000,p.tp+100,p.tp+101,true);assertNotNull(t);assertEquals(p.tp,t.fillPrice,0);assertEquals(p.plannedNetTargetUsdt,t.netResultUsdt,1e-9);}
    @Test public void plannedStopIsExactlyMinusOneRAndIgnoresGap(){FrozenProfitabilityShadowPlan p=build(MarketProfile.eth(),"SHORT",1933.19,2.272,3,1.5,"ETH");FrozenProfitabilityShadowPlan.Terminal t=p.observe(2_000,p.sl+99,p.sl+100,true);assertNotNull(t);assertEquals(p.sl,t.fillPrice,0);assertEquals(-1d,t.resultR,0);assertEquals(-p.plannedNetStopUsdt,t.netResultUsdt,1e-9);}
    @Test public void staleAndInvalidQuotesCannotTerminate(){FrozenProfitabilityShadowPlan p=build(MarketProfile.eth(),"LONG",1923.89,2.186,3,1.5,"ETH");assertNull(p.observe(2_000,p.tp,p.tp,false));assertNull(p.observe(3_000,Double.NaN,p.tp,true));assertFalse(p.terminal());}
    @Test public void stopHasConservativePriorityInAmbiguousFixture(){FrozenProfitabilityShadowPlan p=build(MarketProfile.eth(),"LONG",1923.89,2.186,3,1.5,"ETH");FrozenProfitabilityShadowPlan.Terminal t=p.terminal(2_000,p.entry,true,true);assertEquals("SL_TOUCHED",t.terminalStatus);assertEquals(-1d,t.resultR,0);}
    @Test public void structuralSignatureCrossesFifteenSecondsAndMinute(){FrozenMovementRegistry r=new FrozenMovementRegistry();MarketProfile p=MarketProfile.eth();SignalDecision d=signal(p,"LONG","RANGE_FADE",1,1900,100,90,10);
        String first=r.resolve(p,d,14_999).record.movementSignature;assertEquals(first,r.resolve(p,d,15_001).record.movementSignature);assertEquals(first,r.resolve(p,d,60_001).record.movementSignature);assertEquals(3,r.resolve(p,d,60_002).record.duplicates);}
    @Test public void slightExtremeEvolutionStaysSameMovement(){FrozenMovementRegistry r=new FrozenMovementRegistry();MarketProfile p=MarketProfile.eth();SignalDecision a=signal(p,"LONG","RANGE_FADE",1,1900,100,90,10),b=signal(p,"LONG","RANGE_FADE",1,1900,100,91,10);assertEquals(r.resolve(p,a,1).record.movementSignature,r.resolve(p,b,70_000).record.movementSignature);}
    @Test public void distinctStructureCreatesNewMovement(){FrozenMovementRegistry r=new FrozenMovementRegistry();MarketProfile p=MarketProfile.eth();assertNotEquals(r.resolve(p,signal(p,"LONG","RANGE_FADE",1,1900,100,90,10),1).record.movementSignature,r.resolve(p,signal(p,"LONG","RANGE_FADE",1,1900,130,120,10),2).record.movementSignature);}
    @Test public void movementRegistryIsBoundedPerSymbol(){FrozenMovementRegistry r=new FrozenMovementRegistry();MarketProfile p=MarketProfile.eth();for(int i=0;i<161;i++)r.resolve(p,signal(p,"LONG","RANGE_FADE",1,1900,100+i*20,90+i*20,10),i);assertEquals(160,r.size());assertEquals(1,r.evicted());}
    @Test public void observerBlocksStalePublicActiveAndRearmWithoutPublicMutation(){for(int mode=0;mode<3;mode++){MarketRuntime r=new MarketRuntime(MarketProfile.eth());SignalDecision d=signal(r.profile,"LONG","RANGE_FADE",1,1900,100,90,10);MarketSnapshot s=snapshot(r.profile,1,2.2,"LONG",1900,0,0);r.frozenProfitability.safeObserveRaw(r,s,d,1,mode!=0,true,mode==1,mode!=2);assertNull(r.frozenProfitability.portfolio().active(r.profile.symbol));assertNull(r.activePlan);}}
    @Test public void observerOpensOneEthGroupWithoutPublicPlan(){MarketRuntime r=new MarketRuntime(MarketProfile.eth());r.frozenProfitability.safeObserveRaw(r,snapshot(r.profile,1,2.2,"LONG",1900,0,0),signal(r.profile,"LONG","RANGE_FADE",1,1900,100,90,10),1,true,true,false,true);assertNotNull(r.frozenProfitability.portfolio().active(r.profile.symbol));assertNull(r.activePlan);}
    @Test public void observerOpensTwoSolBranchesButOneOpportunity(){MarketRuntime r=new MarketRuntime(MarketProfile.sol());r.frozenProfitability.safeObserveRaw(r,snapshot(r.profile,1,.077,"SHORT",73.57,2,0),signal(r.profile,"SHORT","CONTINUATION",1,73.57,100,110,10),1,true,true,false,true);FrozenProfitabilityShadowPortfolio.Group g=r.frozenProfitability.portfolio().active(r.profile.symbol);assertNotNull(g);assertEquals(2,g.branches.size());assertEquals(1,((Number)r.frozenProfitability.safeSnapshot(2).get("uniqueOpportunities")).intValue());}
    @Test public void solGroupCooldownStartsAfterBothBranchesResolve(){MarketProfile p=MarketProfile.sol();FrozenProfitabilityShadowPortfolio portfolio=new FrozenProfitabilityShadowPortfolio();FrozenProfitabilityShadowPlan a=build(p,"SHORT",73.57,.077,4,1.5,"CANONICAL"),b=build(p,"SHORT",73.57,.077,4.5,1.75,"ROBUST");portfolio.open(new FrozenProfitabilityShadowPortfolio.Group("opp","movement",p.symbol,1,List.of(a,b)));portfolio.observe(p.symbol,2,a.tp,a.tp,true);assertFalse(portfolio.canOpen(p.symbol,3));portfolio.observe(p.symbol,4,b.tp,b.tp,true);assertFalse(portfolio.canOpen(p.symbol,4+179_999));assertTrue(portfolio.canOpen(p.symbol,4+180_000));}
    @Test public void publicPlanAfterOpenMarksOverlapWithoutClosing(){MarketRuntime r=new MarketRuntime(MarketProfile.eth());MarketSnapshot s=snapshot(r.profile,1,2.2,"LONG",1900,0,0);r.frozenProfitability.safeObserveRaw(r,s,signal(r.profile,"LONG","RANGE_FADE",1,1900,100,90,10),1,true,true,false,true);r.frozenProfitability.safeObserveTerminal(r,s,2,true,true,true);FrozenProfitabilityShadowPortfolio.Group g=r.frozenProfitability.portfolio().active(r.profile.symbol);assertTrue(g.publicOverlap);assertFalse(g.branches.get(0).terminal());}
    @Test public void resetAbortsFrozenBranchesAndPreservesPublicFields(){MarketRuntime r=new MarketRuntime(MarketProfile.eth());MarketSnapshot s=snapshot(r.profile,1,2.2,"LONG",1900,0,0);r.frozenProfitability.safeObserveRaw(r,s,signal(r.profile,"LONG","RANGE_FADE",1,1900,100,90,10),1,true,true,false,true);r.lastTerminalAt=77;r.lastSignal=signal(r.profile,"LONG","RANGE_FADE",1,1900,100,90,10);r.frozenProfitability.safeReset(r,2,false);assertNull(r.frozenProfitability.portfolio().active(r.profile.symbol));assertEquals(77,r.lastTerminalAt);assertNotNull(r.lastSignal);assertTrue(r.recorder.eventMaps().stream().anyMatch(e->"FROZEN_SHADOW_RESET_ABORTED".equals(e.get("eventType"))));}
    @Test public void freshObservedTimeCapsEveryIntervalAtFiveSeconds(){FrozenProfitabilityShadowSummary s=new FrozenProfitabilityShadowSummary();s.observeTime(1_000,true,true);s.observeTime(101_000,true,true);assertEquals(5_000L,s.snapshot(101_000,0,0).get("freshObservedMs"));}
    @Test public void sensitivityBucketsUseExactBoundaries(){SignalDecision eth=signal(MarketProfile.eth(),"LONG","RANGE_FADE",1,1900,100,90,10);assertEquals("ETH_A_2_00_TO_2_18175",FrozenProfitabilityShadowPolicy.sensitivityBucket(MarketProfile.eth(),eth,2.18175,0));SignalDecision sol=signal(MarketProfile.sol(),"LONG","CONTINUATION",1,73,100,90,10);assertEquals("SOL_A_0_052_TO_0_05775|ACCEL_0_30_TO_0_335624",FrozenProfitabilityShadowPolicy.sensitivityBucket(MarketProfile.sol(),sol,.05775,.335624));}
    @Test public void protocolMetadataIsFrozenAndFutureOnly(){Map<String,Object> m=new FrozenProfitabilityShadowSummary().snapshot(1,0,0);assertEquals("FROZEN_PROFITABILITY_SHADOW_V1_20260804",m.get("protocolId"));assertEquals(Boolean.TRUE,m.get("futureHoldoutOnly"));assertEquals(Boolean.FALSE,m.get("publicActivationAllowed"));assertEquals(0L,m.get("TP"));assertEquals(0L,m.get("SL"));}
    @Test public void runtimeFailureBoundaryDoesNotTouchPublicState(){MarketRuntime r=new MarketRuntime(MarketProfile.eth());FrozenProfitabilityShadowObserver bad=new FrozenProfitabilityShadowObserver((op,a)->{throw new IllegalStateException("shadow failed");});r.lastTerminalAt=123;bad.safeObserveRaw(r,snapshot(r.profile,1,2.2,"LONG",1900,0,0),signal(r.profile,"LONG","RANGE_FADE",1,1900,100,90,10),1,true,true,false,true);assertEquals(123,r.lastTerminalAt);assertNull(r.activePlan);}
    @Test public void jsonSnapshotContainsOnlyFiniteNumbers(){MarketRuntime r=new MarketRuntime(MarketProfile.eth());String text=String.valueOf(r.frozenProfitability.safeSnapshot(1));assertFalse(text.contains("NaN"));assertFalse(text.contains("Infinity"));}

    private static FrozenProfitabilityShadowPlan build(MarketProfile profile,String side,double entry,double a,double target,double stop,String branch){SignalDecision d=signal(profile,side,profile==MarketProfile.sol()?"CONTINUATION":"RANGE_FADE",1,entry,100,90,10);double bid="LONG".equals(side)?entry-.01:entry,ask="LONG".equals(side)?entry:entry+.01;FrozenProfitabilityShadowPlan.BuildResult b=FrozenProfitabilityShadowPlan.build(profile,d,1_000,a,"OPP",branch,branch,"MOVE","STRUCTURAL",target,stop,bid,ask,false);assertTrue(b.reasonCode,b.valid());return b.plan;}
    private static SignalDecision signal(MarketProfile p,String side,String family,int score,double entry,double origin,double extreme,double distance){int dir="LONG".equals(side)?1:-1;return SignalDecision.signal(p,side,family,score,1,entry,entry+dir*3,entry-dir,3,1,"P01",true,origin,extreme,distance);}
    private static MarketSnapshot snapshot(MarketProfile p,long now,double a,String side,double entry,double m3,double m8){return snapshotWithM1(p,now,a,side,entry,0,m3,m8);}
    private static MarketSnapshot snapshotWithM1(MarketProfile p,long now,double a,String side,double entry,double m1,double m3,double m8){int d="LONG".equals(side)?1:-1;return MarketSnapshot.builder(now).market(p,entry,entry-.01,entry+.01).btc(60_000,59_999,60_001).averages(a,100).movement(d*m1*a,d*m3*a,d*m8*a,entry+10*a,entry-10*a).move15(0).flow(0,100).professionalFeatures(20*a,1,.5,10*a,10*a,10*a,10*a,0,0,0,0,0,0,0,0,0,0).flowWindows(0,.5,.7,0).btcMoves(0,0,0,0).candleCounts(180,180).build();}
}
