package com.ethscalper.cockpit;
import org.junit.Test;import static org.junit.Assert.*;
public final class V23449CvCoreIntegrationTest {
 @Test public void sameCycleRawABeatsP02CAndOnlyWinnerOpens(){CvCoreMovementRegistry reg=new CvCoreMovementRegistry();CvCoreEngine e=new CvCoreEngine(reg);CvCoreCandidateArbiter arb=new CvCoreCandidateArbiter();arb.beginCycle(100);
  CvCoreMovementRegistry.Episode cEp=reg.observe("ETHUSDT","SHORT",100);CvCoreEngine.Result c=e.observeLegacy("SHORT","CONTINUATION","P02",2,CvCoreTestFixtures.snapshot(1900,1900.01,1.2,0,.0002),CvCoreTestFixtures.metrics(0,0,0,.1,0,.0002),CvCoreTestFixtures.common(),100,cEp);arb.collect(c,CvCoreTestFixtures.snapshot(1900,1900.01,1.2,0,0),100);
  CvCoreMovementRegistry.Episode aEp=reg.observe("ETHUSDT","SHORT",100);CvCoreEngine.Result a=e.observeRaw(CvCoreTestFixtures.signal("SHORT","RANGE_FADE"),CvCoreTestFixtures.snapshot(1900,1900.01,1.2,0,0),CvCoreTestFixtures.metrics(-1,-1,0,1,0,0),CvCoreTestFixtures.common(),100,aEp);arb.collect(a,CvCoreTestFixtures.snapshot(1900,1900.01,1.2,0,0),100);
  CvCoreCandidateArbiter.Resolution r=arb.resolve();assertEquals(CvCorePolicy.DUAL_EXHAUSTION_SHORT,r.winner.result.route);assertEquals(1,r.notSelected.size());assertTrue(e.markOpened(r.winner.result));assertEquals(CvCorePolicy.DUAL_EXHAUSTION_SHORT.routeId,aEp.winningRoute);}
 @Test public void nonQualifyingRawStillFixesEpisode(){CvCoreMovementRegistry reg=new CvCoreMovementRegistry();CvCoreMovementRegistry.Episode ep=reg.observe("ETHUSDT","LONG",1);CvCoreEngine.Result result=new CvCoreEngine(reg).observeRaw(CvCoreTestFixtures.signal("LONG","OTHER"),CvCoreTestFixtures.snapshot(1900,1900.01,1.2,0,0),CvCoreTestFixtures.metrics(0,0,0,0,0,0),CvCoreTestFixtures.common(),1,ep);assertFalse(result.matched());assertNotNull(reg.find(ep.episodeId));}
 @Test public void failedFinalGuardDoesNotMarkEpisode(){CvCoreMovementRegistry reg=new CvCoreMovementRegistry();CvCoreMovementRegistry.Episode ep=reg.observe("ETHUSDT","LONG",1);CvCoreEngine.Result r=new CvCoreEngine(reg).observeRaw(CvCoreTestFixtures.signal("LONG","RANGE_FADE"),CvCoreTestFixtures.snapshot(1900,1900.01,1.2,0,0),CvCoreTestFixtures.metrics(-1,0,0,1,-1,0),CvCoreTestFixtures.common(),1,ep);CvCorePublicationGuard.PublicationResult gate=CvCorePublicationGuard.validate(r.plan,new CvCorePublicationGuard.Context(CvCorePolicy.ENGINE_ID,1,true,true,true,0,0,0,false,false,false,false,1900,1900.01));assertFalse(gate.published);assertFalse(ep.opened);}
 @Test public void realTradingAlwaysDisabled(){assertFalse(SignalSafetyPolicies.realTradingAllowed());}
}
