package com.ethscalper.cockpit;
import org.junit.Test;import static org.junit.Assert.*;
public final class V23449CvCorePublicationGuardTest {
 @Test public void validPasses(){assertTrue(validate(true,true,true,0,0,0,false,false,false,true,1,1900,1900.01).published);}
 @Test public void wrongEngineOrRouteRejected(){CvCorePublicationGuard.Context c=context(true,true,true,0,0,0,false,false,false,true,1,1900,1900.01,"BAD");assertReason("CV_CORE_CONTEXT_INVALID",CvCorePublicationGuard.validate(plan(),c));}
 @Test public void eachStaleFeedHasExactReason(){assertReason("CV_CORE_ETH_FEED_STALE",validate(false,true,true,0,0,0,false,false,false,true,1,1900,1900.01));assertReason("CV_CORE_BTC_FEED_STALE",validate(true,false,true,0,0,0,false,false,false,true,1,1900,1900.01));assertReason("CV_CORE_SOL_FEED_STALE",validate(true,true,false,0,0,0,false,false,false,true,1,1900,1900.01));}
 @Test public void quoteAgeAboveFiveSecondsRejects(){assertReason("CV_CORE_ETH_FEED_STALE",validate(true,true,true,5001,0,0,false,false,false,true,1,1900,1900.01));assertReason("CV_CORE_BTC_FEED_STALE",validate(true,true,true,0,5001,0,false,false,false,true,1,1900,1900.01));assertReason("CV_CORE_SOL_FEED_STALE",validate(true,true,true,0,0,5001,false,false,false,true,1,1900,1900.01));}
 @Test public void activePlanAndEpisodeReject(){assertReason("CV_CORE_PUBLIC_PLAN_ACTIVE",validate(true,true,true,0,0,0,true,false,false,true,1,1900,1900.01));assertReason("CV_CORE_PUBLIC_PLAN_ACTIVE",validate(true,true,true,0,0,0,false,true,false,true,1,1900,1900.01));assertReason("CV_CORE_DUPLICATE_EPISODE",validate(true,true,true,0,0,0,false,false,true,true,1,1900,1900.01));}
 @Test public void expiredOrInvalidQuoteRejects(){assertReason("CV_CORE_ENTRY_WINDOW_EXPIRED",validate(true,true,true,0,0,0,false,false,false,true,6002,1900,1900.01));assertReason("CV_CORE_INVALID_QUOTE",validate(true,true,true,0,0,0,false,false,false,true,1,1901,1900));}
 @Test public void persistenceUnavailableRejects(){assertReason("CV_CORE_PERSISTENCE_FAILED",validate(true,true,true,0,0,0,false,false,false,false,1,1900,1900.01));}
 @Test public void economicsReasonsExact(){assertEquals("CV_CORE_QUANTITY_ZERO",CvCorePublicationGuard.validateEconomics(0,1,.4,1,14.55));assertEquals("CV_CORE_TARGET_NOT_NET_POSITIVE",CvCorePublicationGuard.validateEconomics(1,0,.4,1,14.55));assertEquals("CV_CORE_NET_RR_TOO_LOW",CvCorePublicationGuard.validateEconomics(1,1,.399,1,14.55));assertEquals("CV_CORE_RISK_BUDGET_EXCEEDED",CvCorePublicationGuard.validateEconomics(1,1,.4,14.551,14.55));}
 private static CvCorePlan plan(){return CvCoreTestFixtures.plan(CvCorePolicy.DUAL_EXHAUSTION_SHORT,"SHORT");}
 private static CvCorePublicationGuard.PublicationResult validate(boolean e,boolean b,boolean s,long ea,long ba,long sa,boolean pub,boolean cv,boolean opened,boolean persistence,long now,double bid,double ask){return CvCorePublicationGuard.validate(plan(),context(e,b,s,ea,ba,sa,pub,cv,opened,persistence,now,bid,ask,CvCorePolicy.ENGINE_ID));}
 private static CvCorePublicationGuard.Context context(boolean e,boolean b,boolean s,long ea,long ba,long sa,boolean pub,boolean cv,boolean opened,boolean persistence,long now,double bid,double ask,String engine){return new CvCorePublicationGuard.Context(engine,now,e,b,s,ea,ba,sa,pub,cv,opened,persistence,bid,ask);}
 private static void assertReason(String expected,CvCorePublicationGuard.PublicationResult r){assertFalse(r.published);assertEquals(expected,r.reasonCode);}
}
