package com.ethscalper.cockpit;

import org.junit.Test;
import java.nio.file.Files;
import java.nio.file.Path;
import static org.junit.Assert.*;

public class V4UiContractTest {
    @Test public void mainNavigationIsMinimal()throws Exception{String s=source("src/main/java/com/ethscalper/cockpit/V4MainActivity.java");assertTrue(s.contains("\"ACCUEIL\",\"PLANS\",\"HISTORIQUE\""));assertFalse(s.contains("DIAGNOSTIC\",\"TOOLS"));}
    @Test public void actionableCardHasOperationalFields()throws Exception{String s=source("src/main/java/com/ethscalper/cockpit/V4MainActivity.java");for(String x:new String[]{"QTÉ","ENTRY","TP","SL","ORDRE POSÉ","TRADE PRIS"})assertTrue(s.contains(x));}
    @Test public void noUserLeverageOrPotentialPnlControls()throws Exception{String s=source("src/main/java/com/ethscalper/cockpit/V4MainActivity.java");assertFalse(s.contains("Levier"));assertFalse(s.contains("Gain potentiel"));assertFalse(s.contains("Perte potentielle"));assertFalse(s.contains("PF"));assertFalse(s.contains("Score ML"));}
    @Test public void onlyV4ActivityIsLauncher()throws Exception{String m=source("src/main/AndroidManifest.xml");int main=m.indexOf("android.intent.action.MAIN");assertTrue(main>m.indexOf(".V4MainActivity"));assertTrue(main<m.indexOf(".MainActivity",m.indexOf(".V4MainActivity")+1));}
    @Test public void nativeMaterialThemeUsesNativeActivityNotAppCompat()throws Exception{String activity=source("src/main/java/com/ethscalper/cockpit/V4MainActivity.java"),styles=source("src/main/res/values/styles.xml");
        assertTrue(styles.contains("parent=\"android:style/Theme.Material.NoActionBar\""));assertTrue(activity.contains("import android.app.Activity;"));assertTrue(activity.contains("V4MainActivity extends Activity"));assertFalse(activity.contains("AppCompatActivity"));}
    @Test public void systemInsetsProtectHeaderAndBottomNavigation()throws Exception{String s=source("src/main/java/com/ethscalper/cockpit/V4MainActivity.java");
        assertTrue(s.contains("WindowCompat.setDecorFitsSystemWindows(getWindow(),false)"));assertTrue(s.contains("setOnApplyWindowInsetsListener"));assertTrue(s.contains("WindowInsetsCompat.Type.systemBars()"));assertTrue(s.contains("WindowInsetsCompat.Type.displayCutout()"));assertTrue(s.contains("WindowInsetsCompat.Type.ime()"));assertTrue(s.contains("bottomHost.setPadding"));assertTrue(s.contains("safeBottom+dp(8)"));}
    @Test public void homeAndPlansAreScrollableAndHomeKeepsAllPlans()throws Exception{String s=source("src/main/java/com/ethscalper/cockpit/V4MainActivity.java");
        assertTrue(s.contains("new ScrollView(this)"));assertTrue(s.contains("V4PlanDisplayPolicy.homeOrder"));assertTrue(s.contains("for(int i=1;i<ordered.size();i++)"));assertFalse(s.contains("shown++<1"));assertTrue(s.contains("setNestedScrollingEnabled(false)"));assertTrue(s.contains("setSmoothScrollingEnabled(true)"));
        for(String section:new String[]{"EXÉCUTABLES","ORDRES LIMITES POSSIBLES","EN ATTENTE","ORDRES POSÉS","EN COURS","TERMINÉS / EXPIRÉS"})assertTrue(s.contains(section));}
    @Test public void entryTpSlHaveClipboardActionsAndFeedback()throws Exception{String s=source("src/main/java/com/ethscalper/cockpit/V4MainActivity.java");
        assertTrue(s.contains("ClipboardManager"));assertTrue(s.contains("ClipData.newPlainText"));assertTrue(s.contains("Copier \"+name"));assertTrue(s.contains("\"Copié\""));assertEquals(3,count(s,"addLevel(levels"));}
    @Test public void bottomNavigationHasIconLabelAndSelectionState()throws Exception{String s=source("src/main/java/com/ethscalper/cockpit/V4MainActivity.java");for(String icon:new String[]{"ic_v4_home","ic_v4_plans","ic_v4_history"})assertTrue(s.contains(icon));assertTrue(s.contains("ImageView[] navIcons"));assertTrue(s.contains("TextView[] navLabels"));assertTrue(s.contains("navIcons[i].setColorFilter(color)"));
        for(String path:new String[]{"src/main/res/drawable/ic_v4_home.xml","src/main/res/drawable/ic_v4_plans.xml","src/main/res/drawable/ic_v4_history.xml"})assertTrue(source(path).contains("<vector"));}
    @Test public void runtimeTicksDoNotRebuildUnchangedScrollableContent()throws Exception{String s=source("src/main/java/com/ethscalper/cockpit/V4MainActivity.java");assertTrue(s.contains("contentSignature(runtime)"));assertTrue(s.contains("signature.equals(renderedContentSignature)"));assertTrue(s.indexOf("signature.equals(renderedContentSignature)")<s.indexOf("content.removeAllViews()"));assertFalse(s.contains("NestedScrollView"));}
    @Test public void priceTilesAreCompactNeverEllipsizedAndCopyExactValue()throws Exception{String s=source("src/main/java/com/ethscalper/cockpit/V4MainActivity.java");assertTrue(s.contains("V4PriceDisplay.exact(value)"));assertTrue(s.contains("V4PriceDisplay.compact(value)"));assertTrue(s.contains("price.setEllipsize(null)"));assertTrue(s.contains("new LinearLayout.LayoutParams(dp(31),dp(31))"));assertTrue(source("src/main/res/drawable/ic_v4_copy.xml").contains("<vector"));}
    @Test public void runtimeBadgeUsesRealNetworkSocketFreshnessAndAnalysis()throws Exception{String coordinator=source("src/main/java/com/ethscalper/cockpit/V4RuntimeCoordinator.java"),policy=source("src/main/java/com/ethscalper/cockpit/V4RuntimeStatusPolicy.java"),market=source("src/main/java/com/ethscalper/cockpit/V4MarketDataClient.java");
        assertTrue(coordinator.contains("V4RuntimeStatusPolicy.evaluate"));assertTrue(coordinator.contains("networkAvailable()"));assertTrue(coordinator.contains("NET_CAPABILITY_VALIDATED"));assertTrue(coordinator.contains("scheduleAtFixedRate(this::tick,2,15,TimeUnit.SECONDS)"));assertTrue(coordinator.contains("lastBookTickerAt"));assertTrue(coordinator.contains("lastAnalysisAt"));assertTrue(policy.contains("QUOTE_FRESH_MS = 15_000L"));assertTrue(policy.contains("State { ACTIF, SYNCHRO, HORS_LIGNE }"));assertTrue(market.contains("lastQuoteAt=now"));assertTrue(market.contains("socketConnected=true"));}
    @Test public void emulatorSmokeClicksInsetProtectedBottomNavigation()throws Exception{String s=source("../.github/scripts/android-launch-smoke.sh");assertTrue(s.contains("text') == 'PLANS'"));assertTrue(s.contains("adb shell input tap"));assertTrue(s.contains("ANDROID_BOTTOM_NAV=VISIBLE_AND_CLICKABLE"));}
    private static int count(String source,String needle){int n=0,p=0;while((p=source.indexOf(needle,p))>=0){n++;p+=needle.length();}return n;}
    private static String source(String path)throws Exception{return new String(Files.readAllBytes(Path.of(path)),java.nio.charset.StandardCharsets.UTF_8);}
}
